manager/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'manager'

urlpatterns = [
        path('', views.manager_home, name='manager_home'),
        path('mengelola_tim/', views.mengelola_tim, name='mengelola_tim'),
        path('registrasi/', views.show_timregist, name='show_timregist'),
        path('detail/', views.show_teamdetail, name='show_teamdetail'),
        path('pemain/', views.show_addpemain, name='show_addpemain'),
        path('pelatih/', views.show_addpelatih, name='show_addpelatih'),
        path('update_captain/', views.make_captain, name='make_captain'),
        path('delete_pemain/', views.delete_pemain, name='delete_pemain'),
        path('delete_pelatih/', views.delete_pelatih, name='delete_pelatih'),
        path('add_coach/', views.add_coach, name='add_coach'),
        path('add_player/', views.add_player, name='add_player'),
        path('listpemesanan/', show_listpemesanan, name='show_listpemesanan'),
        path('ketersediaanstadium/', show_ketersediaanstadium, name='show_ketersediaanstadium'),
        path('stadium/', show_memesanstadium, name='show_memesanstadium'),

]

u_league/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tim/', include('manage_tim.urls')),
    path('mulai-rapat/', include('mulai_rapat.urls')),
    path('pembelian/', include('pembelian_tiket.urls')),
    path('', include ('authentication.urls')),
    path('crud_pertandingan/', include('crud_pertandingan.urls')),
    path('cru_peminjamanstadium/', include('cru_peminjamanstadium.urls')),
    path('r_listpertandingan/', include('r_listpertandingan.urls')),
    path('historyrapat/', include('historyrapat.urls')),
    path('manager/', include('manager.urls')),
    path('penonton/', include('penonton.urls')),
    path('panitia/', include('panitia.urls')),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render
from django.contrib import messages
import psycopg2
import locale
import uuid
from utils.query import *
from django.views.decorators.csrf import csrf_exempt

locale.setlocale(locale.LC_ALL, '')
from django.views.decorators.csrf import csrf_exempt

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

@csrf_exempt
def manager_home(request):
    context = {}
    username = request.session['username']
    # manajer = query(f"""
    #             SELECT np.nama_depan, np.nama_belakang, np.nomor_hp, np.email, np.alamat, nps.status, tm.nama_tim
    #             FROM manajer m, non_pemain np, status_non_pemain nps, tim_manajer tm
    #             WHERE m.id_manajer = np.id AND np.id = nps.id_non_pemain AND m.id_manajer = tm.id_manajer AND m.username = '{username}'""")
    
    manajer = query(f"""
                SELECT np.nama_depan, np.nama_belakang, np.nomor_hp, np.email, np.alamat, string_agg(DISTINCT nps.status, ', ') as status, tm.nama_tim, t.universitas, COUNT(DISTINCT p.id_pemain) AS jumlah_pemain, COUNT(DISTINCT pl.id_pelatih) AS jumlah_pelatih
                FROM manajer m
                JOIN non_pemain np ON m.id_manajer = np.id
                LEFT JOIN status_non_pemain nps ON np.id = nps.id_non_pemain
                LEFT JOIN tim_manajer tm ON m.id_manajer = tm.id_manajer
                LEFT JOIN tim t ON tm.nama_tim = t.nama_tim
                LEFT JOIN pemain p ON t.nama_tim = p.nama_tim
                LEFT JOIN pelatih pl ON t.nama_tim = pl.nama_tim
                WHERE m.username = '{username}'
                GROUP BY 1, 2, 3, 4, 5, 7, 8""")

    context = {
        'data_manajer' : manajer
    }
    return render(request, "manager_home.html", context=context)

@csrf_exempt
def mengelola_tim(request):
    username = request.session['username']

    team = query(f"""
    SELECT * FROM Manajer
    NATURAL LEFT JOIN Tim_Manajer
    WHERE Username = '{username}'
    """)

    print("HEY COBA DULU")
    print(team)
    print(team[0]['nama_tim'])

    if team[0]['nama_tim'] is None:
        print("MASUK SINI JUGA PLS")
        print(team[0]['nama_tim'])
        return HttpResponseRedirect(reverse('manager:show_timregist'))
    
    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def show_timregist(request):
    username = request.session['username']

    team = query(f"""
    SELECT * FROM Manajer
    NATURAL LEFT JOIN Tim_Manajer
    WHERE Username = '{username}'
    """)

    if team[0]['nama_tim'] is not None:
        print("MASUK SINI JUGA PLS")
        print(team[0]['nama_tim'])
        return HttpResponseRedirect(reverse('manager:show_teamdetail'))

    if request.method == 'POST':
        team_name = request.POST.get("team_name")
        uni_name = request.POST.get("uni_name")
    
        query_add = query(f"""
        INSERT INTO TIM values ('{team_name}', '{uni_name}')""")
        
        print("\nINI HASILNYA WOI")
        print(query_add)
        print(type(query_add))

        if isinstance(query_add, psycopg2.errors.UniqueViolation):
            # msg = extract_string_before_word(str(query_add), "DETAIL")
            messages.error(request, "Nama tim tidak tersedia")
            print('ERROR NIH')
            return render(request, "teamregist.html")
        
        get_id_manajer = query(f"""
            SELECT ID_Manajer FROM MANAJER 
            WHERE Username = '{username}'""")[0]['id_manajer']
        
        query(f"""INSERT INTO Tim_Manajer values ('{get_id_manajer}', '{team_name}')""")

        return HttpResponseRedirect(reverse('manager:show_teamdetail'))
    
    return render(request, "teamregist.html")

@csrf_exempt
def show_teamdetail(request):
    context = {}

    username = request.session['username']

    nama_tim = get_team(username)


    query_get_pemain = query(f"""
    SELECT Pm.ID_Pemain, CONCAT(Pm.Nama_Depan, ' ', Pm.Nama_Belakang) as Nama_Pemain, Nomor_HP, Tgl_Lahir, Is_Captain, Posisi, NPM, Jenjang 
    FROM PEMAIN Pm WHERE Pm.Nama_Tim = '{nama_tim}'
    """)

    query_get_pelatih = query(f"""
    SELECT Pl.ID_Pelatih, CONCAT(Nama_Depan, ' ', Nama_Belakang) as Nama_Pelatih, 
        Nomor_HP, Email, Alamat, string_agg(Spesialisasi, ', ') as Jenis_Spesialisasi
    FROM Non_Pemain Np, Pelatih Pl, Spesialisasi_Pelatih Sp 
    WHERE Np.ID = Pl.ID_Pelatih
    and Pl.ID_Pelatih = Sp.ID_Pelatih
    and Pl.Nama_Tim = '{nama_tim}'
    group by 1, 2, 3, 4, 5
    """)

    print("halo")
    context = {
        'pemain_list' : query_get_pemain,
        'pelatih_list' : query_get_pelatih,
        'nama_tim' : nama_tim
    }

    return render(request, "teamdetail.html", context=context)

@csrf_exempt
def show_addpemain(request):
    context = {}
    
    pemain_tersedia_list = query(f"""
        SELECT ID_Pemain, CONCAT(Nama_Depan, ' ', Nama_Belakang) as Nama_Pemain, Posisi
        FROM Pemain
        WHERE Nama_Tim is NULL
        ORDER BY Nama_Pemain ASC;
        """)

    context = {
        'pemain_tersedia_list' : pemain_tersedia_list
        }

    return render(request, "addpemain.html", context=context)

@csrf_exempt
def show_addpelatih(request):
    context = {}

    pelatih_tersedia_list = query( f"""
            SELECT Pl.ID_Pelatih, CONCAT(Nama_Depan, ' ', Nama_Belakang) as Nama_Pelatih, string_agg(Spesialisasi, ', ') as Jenis_Spesialisasi
            FROM Non_Pemain Np, Pelatih Pl, Spesialisasi_Pelatih Sp
            WHERE Np.ID = Pl.ID_Pelatih
            and Pl.ID_Pelatih = Sp.ID_Pelatih
            and Pl.Nama_Tim is NULL
            group by 1, 2
            ORDER BY Nama_Pelatih ASC;;
            """)

    context = {
        'pelatih_tersedia_list' : pelatih_tersedia_list
        }
    
    return render(request, "addpelatih.html", context=context)

@csrf_exempt
def add_player(request):
    context = {}
    username = request.session['username']
    nama_tim = get_team(username)

    if request.method == 'POST':
        id_player = request.POST.get("player")    
        testtt = query(f"UPDATE PEMAIN SET Nama_Tim = '{nama_tim}' WHERE ID_Pemain = '{id_player}'")

        print(id_player)
        print(testtt)

    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def add_coach(request):
    context = {}
    username = request.session['username']
    nama_tim = get_team(username)

    if request.method == 'POST':
        id_coach = request.POST.get("coach")    
        query_add = query(f"UPDATE PELATIH SET Nama_Tim = '{nama_tim}' WHERE ID_Pelatih = '{id_coach}'")
        
        print("\nINI HASILNYA YAA")
        print(query_add)
        print(type(query_add))

        if isinstance(query_add, psycopg2.errors.RaiseException):
            msg = extract_string_before_word(str(query_add), "CONTEXT")
            messages.error(request, msg)
            print('ERROR NIH')
            return render(request, 'addpelatih.html', context)

    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def make_captain(request):
    context = {}

    username = request.session['username']
    nama_tim = get_team(username)

    if request.method == 'POST':
        id_new_captain = request.POST.get("capt") 
        print(request.POST)
        print("DISINI")
        print(id_new_captain)   
        query(f"""
        UPDATE PEMAIN
            SET Is_Captain = 'TRUE'
            WHERE Nama_Tim = '{nama_tim}'
            and ID_Pemain = '{id_new_captain}'
        """)

    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def delete_pemain(request):
    context = {}

    if request.method == 'POST':
        id_player = request.POST.get("player")    
        query(f"""
        UPDATE PEMAIN
            SET Nama_Tim = NULL
            WHERE ID_Pemain = '{id_player}'
        """)

    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def delete_pelatih(request):
    context = {}

    if request.method == 'POST':
        id_coach = request.POST.get("coach")

        query(f"""
            UPDATE PELATIH
                SET Nama_Tim = NULL
                WHERE ID_Pelatih = '{id_coach}'
            """)    

        print(cursor)

    return HttpResponseRedirect(reverse('manager:show_teamdetail'))

@csrf_exempt
def get_team(username):
    id_manager = query(f"""
    SELECT id_manajer 
    FROM MANAJER 
    WHERE username='{username}'""")[0]['id_manajer']

    query_get_team = f"""
    SELECT Nama_Tim
        FROM Tim_Manajer
        WHERE ID_Manajer = '{id_manager}'
    """

    the_team = query(query_get_team)

    return the_team[0]['nama_tim']

@csrf_exempt
def extract_string_before_word(string, word):
    split_string = string.split(word)
    if len(split_string) > 1:
        # If the word is found in the string
        return split_string[0]
    else:
        # If the word is not found in the string
        return string

# untuk CRU peminjaman Stadium
def show_listpemesanan(request):
    if request.method == 'GET':

            pemesanan = query("""SELECT nama, date(start_datetime) || ' s.d. ' || date(end_datetime) as waktu FROM stadium s, peminjaman p, manajer m where s.id_stadium = p.id_stadium AND m.id_manajer = p.id_manajer ORDER BY start_datetime asc;""")
                
            print(pemesanan)
            context = {'pemesanan': pemesanan}

            return render(request, 'listpemesan.html', context)

def show_ketersediaanstadium(request):
    context = {}
    
    stadium = query("""
        SELECT id_stadium, nama
        FROM stadium 
        ;
        """)

    context = {
        'stadium' : stadium
        }
    return render(request, "ketersediaanstadium.html", context)

# def add_pesanstadium(request):
#     context = {}
#     # username = "amartusewicz2"
#     # nama_tim = get_team(username)

#     if request.method == 'POST':
#         id_stadium = request.POST.get("stadium")    

manager/templates/addpelatih.html
{% include 'manager_templates.html' %}
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <style>
    p {
      text-align: center;
    }

    label {
      font-size: 12px;
      font-weight: bold;
      color: black;
    }

    .lowbutton {
      font-size: 17px;
      border-radius: 18px;
      width: 18rem;
    }

    .a {
      font-size: 30px;
      font-weight: bold;
      color: black;
      text-align: center;
    }
  </style>
</head>

<body>

  <h2 class="a"> Daftar Pelatih </h1>
    <div class="container mr-2" style="align-items: center;">
    {% for message in messages %}
      <div class="alert alert-danger fade show w-75" role="alert" 
      style="margin-top: 3rem">
        {{ message }}
        <a href="{% url 'manager:show_addpelatih' %}"
        type="button" class="close" 
        style="color: darkred" role="button">&times;</a>
      </div>
    {% endfor %}
    </div>
    
    <form method="POST" action="{% url 'manager:add_coach' %}">
      <div class="p-5 mt-2 mb-2 text-dark">
        {% csrf_token %}
        <table>
          <tr>
            <p class="title-input mt-0 mb-1 ml-3 fw-bold" style="font-size: 15px; text-align:left"> Pelatih yang mau
              didaftarkan:</p>
          </tr>
          <tr>
            <div class="form-floating">
              <select class="form-select form-control" name="coach" id="addPelatih" aria-label="Default select example"
                style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                <option disabled selected>--- Pilih Pelatih ---</option>
                {% for pelatih in pelatih_tersedia_list %}
                <option value={{pelatih.id_pelatih}}> {{pelatih.nama_pelatih}} - {{pelatih.jenis_spesialisasi}} </option>
                {% endfor %}
              </select>
            </div>
          </tr>
        </table>
        <p style="text-align: center">
          <button type="submit" class="btn btn-dark m-3 lowbutton" role="button"
            style="background: #051c2c; color:white"> Submit </button>
        </p>
      </div>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"></script>
</body>

</html>

manager/templates/addpemain.html
{% include 'manager_templates.html' %}
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <style>
    p {
      text-align: center;
    }

    label {
      font-size: 12px;
      font-weight: bold;
      color: black;
    }

    .lowbutton {
      font-size: 17px;
      border-radius: 18px;
      width: 18rem;
    }

    .a {
      font-size: 30px;
      font-weight: bold;
      color: black;
      text-align: center;
    }
  </style>
</head>

<body>
  <h2 class="a"> Daftar Pemain </h1>
    <form method="POST" action="{% url 'manager:add_player' %}">
    <div class="p-5 mt-2 mb-2 text-dark">

      {% csrf_token %}
      <table>
        <tr>
          <p class="title-input mt-0 mb-1 ml-3 fw-bold" style="font-size: 15px; text-align:left"> Pemain yang mau
            didaftarkan:</p>
        </tr>
        <tr>
          <div class="form-floating">
            <select class="form-select form-control" name="player" id="addPemain" aria-label="Default select example"
              style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
              <option disabled selected>--- Pilih Pemain ---</option>
              {% for pemain in pemain_tersedia_list %}
              <option value={{pemain.id_pemain}}> {{pemain.nama_pemain}} - {{pemain.posisi}} </option>
              {% endfor %}
            </select>
          </div>
        </tr>
      </table>
      <p style="text-align: center">
        <button type="submit" class="btn btn-dark m-3 lowbutton" role="button" 
        style="background: #051c2c; color:white"> Submit </button>
      </p>
    </div>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"></script>
</body>

</html>

manager/templates/ketersediaanstadium.html
{% include 'manager_templates.html' %}
{% load static %}
<!doctype html>
<html lang="en">
    
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
  </head>
  <body>
    
    <style>
        .container {
      text-align: center;
      background-color: rgba(255, 255, 255, 0.2);
      padding: 20px;
      border-radius: 10px;
    }
    </style>
<div class="container">
    <h2 class="a"> Peminjaman Stadium </h1>
        <form >
        <div class="p-5 mt-2 mb-2 text-dark">
    
          {% csrf_token %}
          <table>
            <tr>
              <p class="title-input mt-0 mb-1 ml-3 fw-bold" style="font-size: 15px; text-align:center"> Stadium:</p>
            </tr>
            <tr>
              <div class="form-floating">
                <select class="form-select form-control" name="player" id="addPemain" aria-label="Default select example"
                  style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                  <option disabled selected>--- Pilih Stadium ---</option>
                  {% for i in stadium %}
                  <option value={{i.id_stadium}}> {{i.nama}} </option>
                  {% endfor %}
                </select>
                <div class="form-group col-md-6" >
                    <label for="tanggalInput" >Tanggal:</label>
                    <input type="date" class="form-control" id="tanggalInput">
                  </div>
              </div>
            </tr>
          </table>
          <div style="text-align: center;">
            <a href="/manager/stadium/" class="btn text-light p-1" role="button" 
                style="font-size: 14px; border-radius: 14px; width:8rem; background: #1f40cb">
                Submit </a>
          </div>
          
        </div>
        </form>
  </div>
  
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
  crossorigin="anonymous"></script>
  </body>

  </html>

manager/templates/listpemesan.html
{% include 'manager_templates.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Peminjaman Stadium</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    p {
        text-align: center;
    }

    h2 {
        font-size: 12px;
        font-weight: bold;
        color: black;
    }
    
    label{
        font-size: 12px;
        font-weight: bold;
        color: black;
    }

    .card{
        border-radius: 10px;
        height: auto;
        width: auto;
    }
    
    .a{
        font-size: 30px;
        font-weight: bold;
        color: black;
        text-align: center;
    }

    
</style>
</head>
<body>
    <div class="p-3 mt-3 ml-2 mb-0 text-dark" style="text-align: center">
        <h3 class="fw"> List Pemesanan </h3>
    </div> 
    
    <div class="px-5 mt-0 mb-2 mx-5 text-dark" style="font-size: 15px">
    <table class="table table-striped table-bordered" >
      <thead class="thead-dark text-light" style="background: #051c2c">
        <tr>
          <th>Stadium</th>
          <th>Waktu</th>
        </tr>
      </thead>
      <tbody>
          {% for i in pemesanan %}
        <tr>
          <td>{{i.nama}}</td>
          <td>{{i.waktu}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <div style="text-align: center;">
        <a href="/manager/ketersediaanstadium/" class="btn text-light p-1" role="button" 
            style="font-size: 14px; border-radius: 14px; width:8rem; background: #1f40cb">
            Pesan </a>
    </div>
    
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

manager/templates/memesanstadium.html
{% include 'manager_templates.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>List Waktu Stadium</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    
    <style>
        .container {
      text-align: center;
      background-color: rgba(255, 255, 255, 0.2);
      padding: 20px;
      border-radius: 10px;
    }
    </style>
<div class="container">
    <div class="container">
    <h2>List Waktu Stadium </h2>
    <table class="table table-striped table-bordered" >
        <thead class="thead-dark text-light" style="background: #051c2c">
          <tr>
            <th>List Waktu</th>
            <th>Action</th>
          </tr>
        </thead>
      </table>
    </div>
  

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

manager/templates/teamdetail.html
{% include 'manager_templates.html' %}
{% load static %}

{% block content %}
    <style>
        p {
            text-align: center;
        }

        h2 {
            font-size: 12px;
            font-weight: bold;
            color: black;
        }
        
        label{
            font-size: 12px;
            font-weight: bold;
            color: black;
        }

        .card{
            border-radius: 10px;
            height: auto;
            width: auto;
        }
        
        .a{
            font-size: 30px;
            font-weight: bold;
            color: black;
            text-align: center;
        }

        .b{
            font-size: 20px;
            font-weight: bold;
            color: black;
            text-align: center;
        }

        .action {
          font-size: 14px; 
          border-radius: 15px; 
          width:8rem;
        }

        .lowbutton {
          font-size: 17px; 
          border-radius: 18px; 
          width:18rem;
        }

        
    </style>

</head>
<body>
    <h1 class="a" >Tim {{nama_tim}} </h1>
    <div class="container" style="padding: 10px;">
      <div class="p-3 mt-3 ml-2 mb-0 text-dark" style="text-align: center">
        <h4 class="b"> Pemain </h4>
      </div> 

    <div class="p-2 mt-0 mb-2 text-light" style="font-size: 13px">
        <table class="table table-striped table-bordered" >
            <thead class="thead-dark" style="background: #051c2c">
              <tr>
                <th scope="col">Nama Pemain</th>
                <th scope="col">No HP</th>
                <th scope="col">Tanggal Lahir</th>
                <th scope="col">Is Captain</th>
                <th scope="col">Posisi</th>
                <th scope="col">NPM</th>
                <th scope="col">Jenjang</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody class="text-light">
              {% for pemain in pemain_list %}
              <tr>
                <td>{{pemain.nama_pemain}}</td>
                <td>{{pemain.nomor_hp}}</td>
                <td>{{pemain.tgl_lahir}}</td>
                {% if pemain.is_captain == True %}
                  <td> ✅ </td>
                {% elif pemain.is_captain == False %}  
                  <td> ❌ </td>
                {% endif %}
                <td>{{pemain.posisi}}</td>
                <td>{{pemain.npm}}</td>
                <td>{{pemain.jenjang}}</td>
                 
                <td>
                  {% if pemain.is_captain == False %} 
                  <form METHOD="POST" action="{% url 'manager:make_captain' %}"> 
                    {% csrf_token %}
                    <p style="text-align: center; margin-bottom: 3px;">

                        <input class="hidden"  
                          value="{{pemain.id_pemain}}" type="text" name="capt"></input>

                        <button type="submit"  class="action hover:underline" 
                        style="background: #1f40cb"> Make Captain </button>
                        <!-- <a class="btn text-light m-0 action" role="button" 
                          href="{% url 'manager:make_captain' %}"
                          style="background: #1f40cb">
                          Make Captain </a> -->
                    </p>
                  </form>
                  {% endif %}
                  <form METHOD="POST" action="{% url 'manager:delete_pemain' %}"> 
                    {% csrf_token %}
                    <input class="hidden"  
                        value='{{pemain.id_pemain}}' type="text" name="player"></input>
                        <button type="submit"  class="action hover:underline" 
                        style="background: #DC3545"> Delete </button>
                  <!-- <p style="text-align: center">
                      <a class="btn btn-danger text-light m-0 action" role="button">
                        Delete</a> -->
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="p-3 mt-3 ml-2 mb-0 text-dark" style="text-align: center">
      <h4 class="b"> Pelatih </h4>
    </div> 

    <div class="p-2 mt-0 mb-2 text-dark" style="font-size: 13px">
        <table class="table table-striped table-bordered" >
            <thead class="thead-dark text-light" style="background: #051c2c">
              <tr>
                <th scope="col">Nama Pelatih</th>
                <th scope="col">No HP</th>
                <th scope="col">Email</th>
                <th scope="col">Alamat</th>
                <th scope="col">Spesialisasi</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody class="text-light">
              {% for pelatih in pelatih_list %}
              <tr>
                <td>{{pelatih.nama_pelatih}}</td>
                <td>{{pelatih.nomor_hp}}</td>
                <td>{{pelatih.email}}</td>
                <td>{{pelatih.alamat}}</td>
                <td>{{pelatih.jenis_spesialisasi}}</td>
                <td>
                  <form METHOD="POST" action="{% url 'manager:delete_pelatih' %}"> 
                    {% csrf_token %}
                  <input class="hidden"  
                      value='{{pelatih.id_pelatih}}' type="text" name="coach"></input>
                      <button type="submit"  class="action hover:underline" 
                      style="background: #DC3545"> Delete </button> 
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    
    <p style="text-align: center" class="mb-5">
      <a href="{% url 'manager:show_addpemain' %}"
        class="btn btn-dark m-4 lowbutton" 
        style="color: white" role="button">Tambahkan Pemain</a>
      <a href="{% url 'manager:show_addpelatih' %}"
        class="btn btn-dark m-4 lowbutton" role="button" 
        style="color: white">Tambahkan Pelatih</a>
    </p>
    </div>

    {% endblock %}