authentication/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'authentication'

urlpatterns = [
      path('register/', views.register_form, name='register'),
      path('login/', login, name='login'),
      path('logout/', logout, name='logout'),
      path('', views.homepage, name='homepage'),
      path('register/register-manager', views.register_manager, name='register-manager'),
      path('register/register-panitia', views.register_panitia, name='register-panitia'),
      path('register/register-penonton', views.register_penonton, name='register-penonton'),
]

manager/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'manager'

urlpatterns = [
        path('', views.manager_home, name='manager_home'),
        path('mengelola_tim/', views.mengelola_tim, name='mengelola_tim'),
        path('registrasi/', views.show_timregist, name='show_timregist'),
        path('detail/', views.show_teamdetail, name='show_teamdetail'),
        path('pemain/', views.show_addpemain, name='show_addpemain'),
        path('pelatih/', views.show_addpelatih, name='show_addpelatih'),
        path('update_captain/', views.make_captain, name='make_captain'),
        path('delete_pemain/', views.delete_pemain, name='delete_pemain'),
        path('delete_pelatih/', views.delete_pelatih, name='delete_pelatih'),
        path('add_coach/', views.add_coach, name='add_coach'),
        path('add_player/', views.add_player, name='add_player'),
        path('listpemesanan/', show_listpemesanan, name='show_listpemesanan'),
        path('ketersediaanstadium/', show_ketersediaanstadium, name='show_ketersediaanstadium'),
        path('stadium/', show_memesanstadium, name='show_memesanstadium'),

]

panitia/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'panitia'

urlpatterns = [
        path('', views.panitia_home, name='panitia_home'),
        path('kelola_pertandingan/', kelola_pertandingan, name='kelola_pertandingan'),
        path('list/', views.show_homelist, name='show_homelist'),
        path('add/', views.show_addpertandingan, name='show_addpertandingan'),
        path('stadium/', views.show_liststadium, name='show_liststadium'),
        path('buat/', views.show_buatpertandingan, name='show_buatpertandingan'),
        path('pertandingan/', show_pertandingan, name='show_pertandingan'),
        path('rapat/<str:id_pertandingan>/', show_rapat, name='show_rapat'),
        path('mulai_pertandingan/', views.mulai_pertandingan, name='mulai_pertandingan'),
        path('mulai_pertandingan/pilih_peristiwa/', views.pilih_peristiwa, name='pilih_peristiwa'),
        path('incomplete/', show_incomplete, name='show_incomplete'),
        path('tablelist/', show_tablelist, name='show_tablelist'),
        path('listperistiwa/<str:nama_tim>/', show_listperistiwa, name='show_listperistiwa'),
        path('finished/', show_finished, name='show_finished'),
]

u_league/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tim/', include('manage_tim.urls')),
    path('mulai-rapat/', include('mulai_rapat.urls')),
    path('pembelian/', include('pembelian_tiket.urls')),
    path('', include ('authentication.urls')),
    path('crud_pertandingan/', include('crud_pertandingan.urls')),
    path('cru_peminjamanstadium/', include('cru_peminjamanstadium.urls')),
    path('r_listpertandingan/', include('r_listpertandingan.urls')),
    path('historyrapat/', include('historyrapat.urls')),
    path('manager/', include('manager.urls')),
    path('penonton/', include('penonton.urls')),
    path('panitia/', include('panitia.urls')),
]

templates/baseTemplates.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>

        
        <style>
            li{
              color: white;
            }
            a{
              color: white;
              text-decoration:none;
            }

            li:hover {
                text-decoration: none;
                color: #01870E;
            }

            li:active {
                text-decoration: none;
                color: #01870E;
            }

            ul{
                background-color: black;
            }


            .nav {
                width: 100%;
                height: 65px;
                position: fixed;
                line-height: 65px;
                text-align: center;
                z-index: 99999999 !important;
                position: relative;
            }
            .navbar{
                margin-bottom: 70px !important;
            }


          </style>
      </head>
      <body class="max-w-screen min-h-screen  bg-gray-100 text-black">
          <nav class="navbar navbar-default navbar-static-top" style="background-color:black">
            <a class="font-weight-bold" style="color: white; padding-left: 10px;">U-LEAGUE</a>
            </nav>
    
        {% block content %}



        {% endblock %}
    </body>
          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>
          
          

templates/base_templates.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>

        
        <style>
            li{
              color: white;
            }
            a:hover{
              color: white;
              text-decoration:none;
            }

            li:hover {
                text-decoration: none;
                color: #01870E;
            }

            li:active {
                text-decoration: none;
                color: #01870E;
            }

            ul{
                background-color: black;
            }


            .nav {
                width: 100%;
                height: 65px;
                position: fixed;
                line-height: 65px;
                text-align: center;
                z-index: 99999999 !important;
                position: relative;
            }
            .navbar{
                margin-bottom: 70px !important;
            }


          </style>
      </head>
      <body class="max-w-screen min-h-screen  bg-gray-100 text-black">
          <nav class="navbar navbar-default navbar-static-top" style="background-color:black">
            <a href="{% url 'authentication:homepage' %}" class="font-weight-bold" style="color: white; padding-left: 10px;">U-LEAGUE</a>
            </nav>
    
        {% block content %}



        {% endblock %}
    </body>
          <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>
          
          

templates/manager_templates.html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
        <link rel="shortcut icon" href="images/favicon.ico">
      
      <style>
          li{
              color: white;
            }
            a:hover{
              color: white;
              text-decoration:none;
              background-color: #1f40cb;
              font-weight: bold;
            }

            li:active {
                text-decoration: none;
                color:  #FFFFFF;
            }

            ul{
                background-color: black;
            }

            .btn{
            border-radius: 10px;
            }

            .nav {
                width: 100%;
                height: auto;
                line-height: 65px;
                text-align: center;
                z-index: 99999999 !important;
                position: relative;
            }
            .navbar{
                margin-bottom: 70px !important;
            }
            




        </style>
    </head>
    <body>
        <nav class="navbar" style="background-color:black">
          {% if data_manajer %}
          {% for manajer in data_manajer %}
            <p class="font-weight-bold" style="color: white; padding-left: 10px;">
              {{ manajer.nama_depan|upper }} {{ manajer.nama_belakang|upper }} - MANAGER
            </p>
          {% endfor %}
        {% else %}
          <p class="font-weight-bold" style="color: white; padding-left: 10px;">Failed to fetch</p>
        {% endif %}
        


              <ul class="menu menu-horizontal p-0" style="size: 10px; float: right;">
                <li><a href="{% url 'manager:manager_home' %}">Dashboard</a></li>
                <li tabindex="0">
                  <a href="{% url 'manager:mengelola_tim' %}">
                    Mengelola Tim
                  </a>
                </li>
                <li tabindex="1">
                  <a href="{% url 'manager:show_listpemesanan' %}">
                    Peminjaman Stadium
                  </a>
                </li>
                <li tabindex="2">
                    <a>
                      List Pertandingan 
                    </a>
                </li>
                <li tabindex="2">
                  <a>
                    History Rapat
                  </a>
              </li>
              </ul>
            </p>
            <a href="{% url 'authentication:logout' %}" class="btn btn-sm font-weight-bold" style="background-color:#1f40cb; color: white;" >Logout</a>
            
          </nav>
  
      {% block content %}



      {% endblock %}
  </body>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</html>
        
        

templates/panitiaTemplates.html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
      
      <style>
          li{
              color: white;
            }
            a{
              color: white;
              text-decoration:none;
            }

            li:hover {
                text-decoration: none;
                color: #01870E;
            }

            li:active {
                text-decoration: none;
                color: #01870E;
            }

            ul{
                background-color: black;
            }

            .btn{
            border-radius: 10px;
            }

            .nav {
                width: 100%;
                height: 65px;
                position: fixed;
                line-height: 65px;
                text-align: center;
                z-index: 99999999 !important;
                position: relative;
            }
            .navbar{
                margin-bottom: 70px !important;
            }



        </style>
    </head>
    <body>
        <nav class="navbar" style="background-color:black">

            <a class="font-weight-bold" style="color: white; padding-left: 10px;">{{name}} - PANITIA</a>

              <ul class="menu menu-horizontal p-0" style="size: 10px; float: right;">
                <li><a href="/restoran">Dashboard</a></li>
                <li tabindex="0">
                  <a>
                    Jam operasional
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                  <ul class="p-2">
                    <li><a href="/restoran/jadwal/">Lihat Jadwal</a></li>
                    <li><a href="/restoran/jadwal/buat/">Buat Jadwal</a></li>
                  </ul>
                </li>
                <li tabindex="1">
                  <a>
                    Makanan
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                  </a>
                  <ul class="p-2">
                    <li><a href="/restoran/menu/" >Daftar Menu</a></li>
                    <li><a href="/restoran/menu/create/" >Tambah Menu</a></li>
                  </ul>
              </li>
                <li tabindex="2">
                    <a>
                      Pesanan
                      <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                    </a>
                    <ul class="p-2">
                      <li><a href="/restoran/pesanan/">Lihat semua pesanan</a></li>
                      <li><a href="/restoran/pesanan/ongoing/">pesanan berlangsung</a></li>
                    </ul>
                </li>
                <li tabindex="2">
                  <a>
                    Promo
                    <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
                  </a>
                  <ul class="p-2">
                    <li><a href="{% url 'adminRole:daftar-tarif-pengiriman' %}">Daftar promo tersedia</a></li>
                    <li><a href="{% url 'adminRole:tarif-pengiriman' %}">Daftar promo restoran</a></li>
                  </ul>
              </li>
              <li><a href="/restopay">Restopay</a></li>
              </ul>

            <a href="{% url 'authentication:logout' %}" class="btn btn-sm font-weight-bold" style="background-color: #01870E; color: white;" >Logout</a>
            
          </nav>
  
      {% block content %}



      {% endblock %}
  </body>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</html>
        
        

templates/panitia_templates.html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
        
      
      <style>
        li{
          color: white;
        }
        a:hover{
          color: white;
          text-decoration:none;
          background-color: #1f40cb;
          font-weight: bold;

        }
        li:active {
            text-decoration: none;
            color: #FFFFFF;
        }

        ul{
            background-color: black;
        }

        .btn{
        border-radius: 10px;
        }

        .nav {
            width: 100%;
            height: auto;
            line-height: 65px;
            text-align: center;
            z-index: 99999999 !important;
            position: relative;
        }
        .navbar{
            margin-bottom: 70px !important;
        }



        </style>
    </head>
    <body>
        <nav class="navbar" style="background-color:black">
          {% if data_panitia %}
          {% for panitia in data_panitia %}
            <p class="font-weight-bold" style="color: white; padding-left: 10px;">
              {{ panitia.nama_depan|upper }} {{ panitia.nama_belakang|upper }} - PANITIA
            </p>
          {% endfor %}
        {% else %}
          <p class="font-weight-bold" style="color: white; padding-left: 10px;">Failed to fetch</p>
        {% endif %}
              <ul class="menu menu-horizontal p-0" style="size: 10px; float: right;">
                <li><a href="{% url 'panitia:panitia_home' %}">Dashboard</a></li>
                <li tabindex="0">
                  <a href="{% url 'panitia:show_pertandingan' %}">Rapat</a> 
                </li>
                <li tabindex="0">
                  <a href="{% url 'panitia:kelola_pertandingan' %}">
                    Manage Pertandingan 
                  </a>
              </li>
            </ul>

            <a href="{% url 'authentication:logout' %}" class="btn btn-sm font-weight-bold" style="background-color: #1f40cb; color: white;" >Logout</a>            
          </nav>
  
      {% block content %}



      {% endblock %}
  </body>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</html>
        
        

templates/penonton_templates.html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@2.41.0/dist/full.css" rel="stylesheet" type="text/css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <title>U-LEAGUE</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
      
      <style>
        li{
          color: white;
        }
        a:hover{
          color: white;
          text-decoration:none;
          background-color: #1f40cb;
          font-weight: bold;

        }
        li:active {
            text-decoration: none;
            color: #FFFFFF;
        }

        ul{
          background-color: black;
        }

        .btn{
        border-radius: 10px;
        }

        .nav {
            width: 100%;
            height: auto;
            line-height: 65px;
            text-align: center;
            z-index: 99999999 !important;
            position: relative;
        }
        .navbar{
            margin-bottom: 70px !important;
        }



        </style>
    </head>
    <body>
        <nav class="navbar" style="background-color:black">

            <p class="font-weight-bold" style="color: white; padding-left: 15px;">TEST - PENONTON</p>

              <ul class="menu menu-horizontal p-0" style="size: 10px; float: right;">
                <li><a href="">Dashboard</a></li>
                <li tabindex="0">
                  <a href=""> 
                    Pembelian Tiket
                  </a>
                <li tabindex="1">
                  <a href="">
                    List Pertandingan
                  </a>
              </li>
            </ul>
            <a href="{% url 'authentication:logout' %}" class="btn btn-sm font-weight-bold" style="background-color: #1f40cb; color: white;" >Logout</a>      
          </nav>
  
      {% block content %}



      {% endblock %}
  </body>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</html>
        
        