manager/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'manager'

urlpatterns = [
        path('', views.manager_home, name='manager_home'),
        path('mengelola_tim/', views.mengelola_tim, name='mengelola_tim'),
        path('registrasi/', views.show_timregist, name='show_timregist'),
        path('detail/', views.show_teamdetail, name='show_teamdetail'),
        path('pemain/', views.show_addpemain, name='show_addpemain'),
        path('pelatih/', views.show_addpelatih, name='show_addpelatih'),
        path('update_captain/', views.make_captain, name='make_captain'),
        path('delete_pemain/', views.delete_pemain, name='delete_pemain'),
        path('delete_pelatih/', views.delete_pelatih, name='delete_pelatih'),
        path('add_coach/', views.add_coach, name='add_coach'),
        path('add_player/', views.add_player, name='add_player'),
        path('listpemesanan/', show_listpemesanan, name='show_listpemesanan'),
        path('ketersediaanstadium/', show_ketersediaanstadium, name='show_ketersediaanstadium'),
        path('stadium/', show_memesanstadium, name='show_memesanstadium'),

]

mulai_pertandingan/urls.py
#sfrom django.urls import path
#from mulai_pertandingan.views import show_mulaipertandingan, show_pilihperistiwa

#app_name = 'mulai_pertandingan'

#urlpatterns = [
    #path('', show_mulaipertandingan, name='show_mulaipertandingan'),
    #path('peristiwa', show_pilihperistiwa, name='show_mulaipertandingan'),
#]

panitia/urls.py
from django.urls import path 
from . import views
from .views import *

app_name = 'panitia'

urlpatterns = [
        path('', views.panitia_home, name='panitia_home'),
        path('kelola_pertandingan/', kelola_pertandingan, name='kelola_pertandingan'),
        path('list/', views.show_homelist, name='show_homelist'),
        path('add/', views.show_addpertandingan, name='show_addpertandingan'),
        path('stadium/', views.show_liststadium, name='show_liststadium'),
        path('buat/', views.show_buatpertandingan, name='show_buatpertandingan'),
        path('pertandingan/', show_pertandingan, name='show_pertandingan'),
        path('rapat/<str:id_pertandingan>/', show_rapat, name='show_rapat'),
        path('mulai_pertandingan/', views.mulai_pertandingan, name='mulai_pertandingan'),
        path('mulai_pertandingan/pilih_peristiwa/', views.pilih_peristiwa, name='pilih_peristiwa'),
        path('incomplete/', show_incomplete, name='show_incomplete'),
        path('tablelist/', show_tablelist, name='show_tablelist'),
        path('listperistiwa/<str:nama_tim>/', show_listperistiwa, name='show_listperistiwa'),
        path('finished/', show_finished, name='show_finished'),
]

u_league/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tim/', include('manage_tim.urls')),
    path('mulai-rapat/', include('mulai_rapat.urls')),
    path('pembelian/', include('pembelian_tiket.urls')),
    path('', include ('authentication.urls')),
    path('crud_pertandingan/', include('crud_pertandingan.urls')),
    path('cru_peminjamanstadium/', include('cru_peminjamanstadium.urls')),
    path('r_listpertandingan/', include('r_listpertandingan.urls')),
    path('historyrapat/', include('historyrapat.urls')),
    path('manager/', include('manager.urls')),
    path('penonton/', include('penonton.urls')),
    path('panitia/', include('panitia.urls')),
]

panitia/models.py
from django.db import models

# Create your models here.

mulai_pertandingan/views.py
from django.shortcuts import render

# Create your views here.
#def show_mulaipertandingan(request):
    #return render(request, "mulaipertandingan.html")

#def show_pilihperistiwa(request):
    #return render(request, "pilihperistiwa.html")

panitia/views.py
from django.shortcuts import render
from django.contrib import messages
import psycopg2
import locale
import uuid
from utils.query import *
from django.views.decorators.csrf import csrf_exempt
from manager import views as manager_views
locale.setlocale(locale.LC_ALL, '')
from django.views.decorators.csrf import csrf_exempt

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

@csrf_exempt
def panitia_home(request):
    context = {}
    username = request.session['username']
    
    panitia = query(f"""
                    SELECT np.nama_depan, np.nama_belakang, np.nomor_hp, np.email, np.alamat, string_agg(DISTINCT nps.status, ', ') as status, p.jabatan, r.datetime
                    FROM panitia p
                    JOIN non_pemain np ON p.id_panitia = np.id
                    LEFT JOIN status_non_pemain nps ON np.id = nps.id_non_pemain
                    LEFT JOIN rapat r ON p.id_panitia = r.perwakilan_panitia
                    WHERE p.username = '{username}'
                    GROUP BY 1, 2, 3, 4, 5, 7, 8""")
    context = {
        'data_panitia' : panitia
    }
    return render(request, 'panitia_home.html', context=context)

def show_homelist(request):
    return render(request, "homelist.html")

def show_addpertandingan(request):
    return render(request, "addpertandingan.html")

def show_liststadium(request):
    return render(request, "liststadium.html")

def show_buatpertandingan(request):
    return render(request, "buatpertandingan.html")

# untuk rapat
def show_rapat(request, id_pertandingan):
    if request.method == 'GET':

            pertandingan = query("""SELECT r.id_pertandingan, string_agg(nama_tim, ' vs ') as tim_bertanding, s.nama, datetime
                                FROM rapat r, pertandingan p, tim_pertandingan tp, stadium s 
                                WHERE r.id_pertandingan = p.id_pertandingan AND p.id_pertandingan = tp.id_pertandingan AND p.stadium = s.id_stadium AND r.id_pertandingan = '{}'
                                GROUP BY r.id_pertandingan, stadium, s.nama, datetime;""".format(id_pertandingan))
                
            print(pertandingan)
            context = {'pertandingan': pertandingan}

            return render(request, 'rapat.html', context)

    if request.method == 'POST':
        isi_rapat = request.POST.get("rapat")
        
        query(f"""UPDATE RAPAT 
            SET isi_rapat = '{isi_rapat}'
            WHERE id_pertandingan = '{id_pertandingan}'""")
        
        return HttpResponseRedirect(reverse('panitia:show_pertandingan'))
    
    return render(request, 'rapat.html')

def mulai_pertandingan(request):
    context = {}
    
    username = request.session['username']
    
    tim1_info = query(f"""
                     SELECT distinct t.nama_tim
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_a
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1""")
    
    tim2_info = query(f"""
                       SELECT distinct t.nama_tim
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_a
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1""")
    
    context = {
        'tim1_info' : tim1_info,
        'tim2_info' : tim2_info
    }
    
    return render(request, "mulaipertandingan.html", context=context)
    
    
    
    return render(request, "mulaipertandingan.html")

def pilih_peristiwa(request):
    return render(request, "pilihperistiwa.html")

def show_incomplete(request):
    return render(request, "incomplete.html")

def show_listperistiwa(request, nama_tim):
    context = {}
    
    username = request.session['username']
    
    nama_pemain_A = query(f"""
                        SELECT distinct pm.nama_depan, pm.nama_belakang, t.nama_tim
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_a
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1, 2, 3""".format(nama_tim))
    
    peristiwa_A = query(f"""
                        SELECT distinct pr.jenis
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_a
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1""".format(nama_tim))
    
    nama_pemain_B = query(f"""
                        SELECT distinct pm.nama_depan, pm.nama_belakang, t.nama_tim
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_b
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1, 2, 3""".format(nama_tim))
    
    peristiwa_B = query(f"""
                        SELECT distinct pr.jenis
                        FROM pemain pm, peristiwa pr, pertandingan p, tim_pertandingan tp, tim t, rapat r, panitia pa, tim_manajer tm
                        WHERE pr.id_pemain = pm.id_pemain AND pr.id_pertandingan = p.id_pertandingan
                        AND p.id_pertandingan = tp.id_pertandingan AND tp.nama_tim = t.nama_tim
                        AND tm.nama_tim = t.nama_tim AND tm.id_manajer = r.manajer_tim_b
                        AND r.perwakilan_panitia = pa.id_panitia AND pa.username = '{username}'
                        GROUP BY 1""".format(nama_tim))
    
    
    context = {
        'nama_pemainA' : nama_pemain_A,
        'peristiwaA' : peristiwa_A,
        'nama_pemainB' : nama_pemain_B,
        'peristiwaB' : peristiwa_B
        
    }
    
    return render(request, "listperistiwa.html", context=context)

@csrf_exempt
def show_tablelist(request):
    context = {}
    
    username = request.session['username']
    
    tim1_query = query(f"""
                        SELECT t.nama_tim, p.start_datetime, tp.skor
                        FROM pertandingan p
                        JOIN tim_pertandingan tp ON p.id_pertandingan = tp.id_pertandingan
                        JOIN tim t ON tp.nama_tim = t.nama_tim
                        LEFT JOIN tim_manajer tm ON t.nama_tim = tm.nama_tim
                        LEFT JOIN rapat r ON tm.id_manajer = r.manajer_tim_a
                        LEFT JOIN panitia pa ON r.perwakilan_panitia = pa.id_panitia
                        WHERE pa.username = '{username}'
                        GROUP BY 1, 2, 3""")
    
    tim2_query = query(f"""
                        SELECT t.nama_tim, p.start_datetime , tp.skor
                        FROM pertandingan p
                        JOIN tim_pertandingan tp ON p.id_pertandingan = tp.id_pertandingan
                        JOIN tim t ON tp.nama_tim = t.nama_tim
                        LEFT JOIN tim_manajer tm ON t.nama_tim = tm.nama_tim
                        LEFT JOIN rapat r ON tm.id_manajer = r.manajer_tim_b
                        LEFT JOIN panitia pa ON r.perwakilan_panitia = pa.id_panitia
                        WHERE pa.username = '{username}'
                        GROUP BY 1, 2, 3""")
    
    nama_tim1 = tim1_query[0]['nama_tim']
    nama_tim2 = tim2_query[0]['nama_tim']
    
    skor_tim1 = tim1_query[0]['skor']
    skor_tim2 = tim2_query[0]['skor']
    
    pemenang_query = query(f"""
                           SELECT 
                           CASE 
                           WHEN CAST('{skor_tim1}' AS INTEGER) > CAST('{skor_tim2}' AS INTEGER) THEN '{nama_tim1}'
                           WHEN CAST('{skor_tim1}' AS INTEGER) < CAST('{skor_tim2}' AS INTEGER) THEN '{nama_tim2}'
                           END AS pemenang
                           FROM tim_pertandingan tp
                           JOIN pertandingan p ON tp.id_pertandingan = p.id_pertandingan
                           JOIN rapat r ON p.id_pertandingan = r.id_pertandingan
                           JOIN panitia pa ON r.perwakilan_panitia = pa.id_panitia
                           WHERE pa.username = '{username}'
                           GROUP BY 1""")
    
                               
    time_pertandingan = query(f"""

panitia/templates/addpertandingan.html
{% include 'panitia_templates.html' %}
{% load static %}

{% block content %}
    <style>
      p {
          text-align: center;
      }
      
      label{
          font-size: 12px;
          font-weight: bold;
          color: black;
      }

      .lowbutton {
        font-size: 17px; 
        border-radius: 18px; 
        width:18rem;
      }

      .a{
            font-size: 30px;
            font-weight: bold;
            color: black;
            text-align: center;
        }

        .lowbutton {
        font-size: 17px; 
        border-radius: 18px; 
        width:18rem;
      }

      
  </style>
</head>

<body>
    <h2 class="a"> Pembuatan Pertandingan </h1>

    <div class="p-5 mt-2 mb-2 text-dark">
        <form method="POST" id="addPertandinganForm">
            {% csrf_token %}
            <table>
                <tr>
                    <p class="title-input mt-0 mb-1 ml-3 fw-bold" style="font-size: 15px; text-align:left"> Stadium </p>
                </tr>
                <tr>
                    <div class="form-floating">
                        <select class="form-select form-control" name="pemain" id="addPertandingan"
                            aria-label="Default select example"
                            style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                            <option disabled selected>--- Stadium-stadium yang tersedia ---</option>
                            <option value="Stadium Gelora Bung Karno"> Stadium Gelora Bung Karno </option>
                            <option value="Stadium Senayan"> Stadium Senayan </option>
                            <option value="..."> ... </option>
                        </select>
                    </div>
                </tr>
                <tr>
                    <label class="title-input mt-3 mb-1 ml-3 fw-bold" 
                        style="font-size: 15px; height: auto; text-align:left;"
                        for="tanggal">Tanggal:   </label>
                    <input style="background:white; border-color: black; margin: 10px;"
                        type="date" id="tanggal" name="tanggal">
                </tr>
            </table>
        </form>
    </div>

    <p style="text-align: center">
        <a href="{% url 'panitia:show_buatpertandingan' %}"
            class="btn btn-dark m-3 lowbutton" 
            role="button"  style="color:white"> Next</a>
    </p>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

{% endblock %}

panitia/templates/buatpertandingan.html
{% include 'panitia_templates.html' %}
{% load static %}

{% block content %}
    <style>
      p {
          text-align: center;
      }
      
      label{
          font-size: 12px;
          font-weight: bold;
          color: black;
      }

      .lowbutton {
        font-size: 17px; 
        border-radius: 18px; 
        width:18rem;
      }

      .a{
            font-size: 30px;
            font-weight: bold;
            color: black;
            text-align: center;
        }

        .lowbutton {
        font-size: 17px; 
        border-radius: 18px; 
        width:18rem;
      }

      
  </style>
  
</head>

<body>
    <h2 class="a"> Buat Pertandingan </h1>

    <div class="p-5 mt-2 mb-2 text-dark">
        <form method="POST" id="buatPertandinganForm">
            {% csrf_token %}
            <table>
                <tr>
                    <div class="form-floating mb-3">
                        <label for="addWasitUtama"> Pilih Wasit Utama </label>
                        <select class="form-select form-control" name="pemain" id="addWasitUtama"
                            aria-label="Default select example"
                            style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                            <option disabled selected>--- Wasit yang tersedia ---</option>
                            <option value="Wasit AAA"> Wasit AAA </option>
                            <option value="Wasit BBB"> Wasit BBB </option>
                            <option value="Wasit BBB"> Wasit CCC </option>
                            <option value="..."> ... </option>
                        </select>
                    </div>
                </tr>
                <tr>
                    <div class="form-floating mb-3">
                        <label for="addWasitPembantu1"> Pilih Wasit Pembantu/Hakim Garis </label>
                        <select class="form-select form-control" name="pemain" id="addWasitPembantu1"
                            aria-label="Default select example"
                            style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                            <option disabled selected>--- Wasit yang tersedia ---</option>
                            <option value="Wasit AAA"> Wasit AAA </option>
                            <option value="Wasit BBB"> Wasit BBB </option>
                            <option value="Wasit BBB"> Wasit CCC </option>
                            <option value="..."> ... </option>
                        </select>
                    </div>
                </tr>
                <tr>
                    <div class="form-floating mb-3">
                        <label for="addWasitPembantu2"> Pilih Wasit Pembantu/Hakim Garis </label>
                        <select class="form-select form-control" name="pemain" id="addWasitPembantu2"
                            aria-label="Default select example"
                            style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                            <option disabled selected>--- Wasit yang tersedia ---</option>
                            <option value="Wasit AAA"> Wasit AAA </option>
                            <option value="Wasit BBB"> Wasit BBB </option>
                            <option value="Wasit BBB"> Wasit CCC </option>
                            <option value="..."> ... </option>
                        </select>
                    </div>
                </tr>
                <tr>
                    <div class="form-floating mb-3">
                        <label for="addWasitCadangan"> Pilih Wasit Cadangan </label>
                        <select class="form-select form-control" name="pemain" id="addWasitCadangan"
                            aria-label="Default select example"
                            style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5;">
                            <option disabled selected>--- Wasit yang tersedia ---</option>
                            <option value="Wasit AAA"> Wasit AAA </option>
                            <option value="Wasit BBB"> Wasit BBB </option>
                            <option value="Wasit BBB"> Wasit CCC </option>
                            <option value="..."> ... </option>
                        </select>
                    </div>
                </tr>
                <tr>
                    <td>
                        <p class="title-input mt-0 mb-1 mx-2 fw-bold" 
                        style="font-size: 15px; font-weight: bold; text-align:left"> Tim 1:  </p>
                    </td>
                    <td>
                        <div class="form-floating">
                            <select class="form-select form-control" name="pemain" id="addTim1"
                                aria-label="Default select example"
                                style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5; width: 30rem">
                                <option disabled selected>--- Tim yang sudah mendaftar di stadium ---</option>
                                <option value="Tim QWERTY" > Tim QWERTY </option>
                                <option value="Tim TYUIOP" > Tim TYUIOP </option>
                                <option value="..." > ... </option>
                            </select>
                        </div>
                    </td>
                    <td>
                        <p class="title-input mt-0 mb-1 ml-5 mx-2 fw-bold" 
                        style="font-size: 15px; font-weight: bold; text-align:left"> Tim 2:  </p>
                    </td>
                    <td>
                        <div class="form-floating">
                            <select class="form-select form-control" name="pemain" id="addTim2"
                                aria-label="Default select example"
                                style="padding-top: 1rem; padding-bottom: 0rem;font-size:13px; height: 3.5rem; line-height: 1.5; width: 30rem">
                                <option disabled selected>--- Tim yang sudah mendaftar di stadium ---</option>
                                <option value="Tim QWERTY" > Tim QWERTY </option>
                                <option value="Tim TYUIOP" > Tim TYUIOP </option>
                                <option value="..." > ... </option>
                            </select>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>

    <p style="text-align: center">
        <a href="{% url 'panitia:show_homelist' %}"
            class="btn btn-dark m-3 lowbutton" 
            role="button"  style="color:white"> Submit</a>
    </p>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

{% endblock %}

panitia/templates/finished.html
{% include 'panitia_templates.html'%}
{% load static %}

{% block content %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <style>
  </style>
</head>

<body>
    <div class="p-5 mb-1 text-light" style="background: #051c2c">
        <h2 class="fw"> Kelola Pertandingan </h>
    </div> 

    <div class="p-3 mt-5 ml-0 mb-0 text-dark" style="text-align: center">
        <h4 class="fw" style="font-size: 32px"> INI AKHIR MUSIM! </h3>
    </div> 

    <div class="p-2 mt-0 ml-0 mb-1 text-dark" style="text-align: center">
        <h4 class="fw" style="font-size: 16px"> KLIK TOMBOL NEXT UNTUK MEMBUAT PERTANDINGAN BARU </h3>
    </div> 

    <p style="text-align: center">
      <a class="btn btn-dark m-3" role="button" 
        style="font-size: 17px; border-radius: 20px; width:15rem">Next</a>
    </p>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</body>

{% endblock %}

panitia/templates/incomplete.html
{% include 'panitia_templates.html'%}
{% load static %}

{% block content %}

<body>
    <div class="p-5 mb-1 text-light w-full" style="background: #051c2c">
        <h1 class="fw text-4xl text-center"> Kelola Pertandingan </h1>
    </div> 

    <div class="p-3 mt-5 ml-0 mb-0 text-dark" style="text-align: center">
        <h4 class="fw" style="font-size: 27px"> PERTANDINGAN BELUM LENGKAP! </h3>
    </div> 

    <div class="p-2 mt-0 ml-0 mb-1 text-dark" style="text-align: center">
        <h4 class="fw" style="font-size: 16px"> KLIK TOMBOL NEXT UNTUK MEMBUAT PERTANDINGAN </h3>
    </div> 

    <p style="text-align: center">
      <a href="{% url 'panitia:show_addpertandingan' %}" class="btn btn-dark text-light m-3" role="button" 
        style="font-size: 17px; border-radius: 20px; width:15rem;">Next</a>
    </p>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"></script>
</body>

{% endblock %}

panitia/templates/mulaipertandingan.html
{% include "panitia_templates.html" %}
{% load static %}

{% block content %}
  <style>
    .buttonSubmit{
      text-align: center;
      margin-bottom: 5px;
      text-decoration: none;
    } 
  </style>
  
</head>
<body>
  <div class="px-5 mt-0 mb-0 mx-5 text-dark" style="font-size: 30px; font-weight: bold">
    
    <table class="table table-striped table-bordered">
      <thead class="thead-dark text-light" style="background: #051c2c">
        <div class="p-3 mt-3 ml-2 mb-0 text-dark" style="text-align: center">
          {% for i in tim1_info %}
          {% for j in tim2_info %}
          <h3 class="fw"> Pilih Peristiwa Tim {{i.nama_tim}} </h3>
        </div> 
        <tr>
          <th>Tim 1</th>
          <th>Tim 2</th>
          <th>Peristiwa</th>
        </tr>
      </thead>
      <tbody class="text-light">
        <tr>
          <td>{{i.nama_tim}}</td>
          <td>Fulham</td>
          <td><a href="{% url 'panitia:pilih_peristiwa' %}" class="btn text-light p-1" role="button" 
            style="font-size: 14px; border-radius: 14px; width:15rem; background: #1f40cb">
            Masukkan Peristiwa Tim 1</a>
          <a href="{% url 'panitia:pilih_peristiwa' %}" class="btn text-light p-1" role="button" 
            style="font-size: 14px; border-radius: 14px; width:15rem; background: #1f40cb">
            Masukkan Peristiwa Tim 2</a></td>
        </tr>     
      </tbody>
      {% endfor %}
      {% endfor %}
    </table>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br>
    <div class="buttonSubmit" style="text-align: center">
        <a class="btn btn-dark m-3" role="button" 
          style="font-size: 17px; border-radius: 20px; width:12rem; color:white">Submit</a>
    </div>
  </div>
{% endblock %}